# Generated by Django 4.2.3 on 2023-07-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote_History',
        ),
        migrations.AddField(
            model_name='quote',
            name='username',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
    ]
