# Generated by Django 4.2.2 on 2023-06-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='amount',
        ),
        migrations.AddField(
            model_name='quote',
            name='delivery_address',
            field=models.CharField(default='Houston', max_length=200),
        ),
        migrations.AddField(
            model_name='quote',
            name='gallons_requested',
            field=models.DecimalField(decimal_places=2, default=7, max_digits=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
