# Generated by Django 4.2.2 on 2023-08-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='suggested_price',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=10),
        ),
    ]
