# Generated by Django 4.2.2 on 2023-08-01 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_quote_suggested_price'),
        ('quotes', '0002_profile'),
    ]

    operations = [
    ]
