# Generated by Django 4.2.2 on 2023-08-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_merge_0002_alter_quote_suggested_price_0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='mr_sir', max_length=50),
            preserve_default=False,
        ),
    ]
